In [2]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

## Задание 1

In [9]:
def gennerate_array(reverse = True):
    page = int(input('Введите конец массива')) + 1
    gennerate_array = np.arange(0, page)
    if reverse == True:
        return gennerate_array[np.argpartition(-gennerate_array, np.arange((~np.isnan(gennerate_array)).sum()))]
    else:
        return gennerate_array

In [12]:
gennerate_array(reverse = False)

Введите конец массива 15


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
gennerate_array(reverse = True)

Введите конец массива 15


array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2

In [34]:
def diagonal_sum():
    a = np.diagflat(gennerate_array())
    sums = sum(np.diagonal(a))
    return sums

In [35]:
diagonal_sum()

Введите конец массива 100000


5000050000

## Задание 3

4x + 2y + z = 4 & x + 3y = 12 & 5y + 4z = -3

In [21]:
left = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
right = np.array([4, 12, -3])
np.linalg.solve(left, right)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4

In [58]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [56]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [124]:
#dot - произведение векторов для 1-D массивов
#norm(a, b, no args) - Норма Фробениуса

def cos_max(word_interp = False):
    cos_dict = {}
    for num, element in enumerate(users_stats):
        solve = dot(list(element), list(next_user_stats))/(norm(list(element))*norm(list(next_user_stats)))
        cos_dict[num] = solve
        
    if word_interp == True:
        return print(f'Юзер {max(cos_dict, key=cos_dict.get)},\
        \n самый похожий с новым пользователем\
        \n и имеет коэффициент {max(cos_dict.values())}')
    else:
        return cos_dict

cos_max()

{0: 0.19999999999999996,
 1: 0.8451542547285165,
 2: 0.3999999999999999,
 3: 0.7905694150420948,
 4: 0.3999999999999999,
 5: 0.0,
 6: 0.0,
 7: 0.9486832980505138,
 8: 0.0,
 9: 0.0}

In [125]:
cos_max(word_interp = True)

Юзер 7,        
 самый похожий с новым пользователем        
 и имеет коэффициент 0.9486832980505138
